In [ ]:
# Necessary imports

import tensorflow as tf

### 1. Create a vector, scalar, matrix and tensor with values using `tf.constant()` ###

In [ ]:
scalar = tf.constant(5)
vector = tf.constant([1, 2])
matrix = tf.constant([[1, 2], [3, 4]])
tensor = tf.constant([[[1,2], [3,4]], [[5, 6], [7,8]]])

### 2. Find the shape of the tensors created in 1. ###

In [ ]:
print(f"Scalar's shape: {scalar.shape}")
print(f"Vector's shape: {vector.shape}")
print(f"Matrix's shape: {matrix.shape}")
print(f"Tensor's shape: {tensor.shape}")

Scalar's shape: ()
Vector's shape: (2,)
Matrix's shape: (2, 2)
Tensor's shape: (2, 2, 2)


### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300]. ###

In [ ]:
t1 = tf.random.uniform(shape = (5,300), minval = 0, maxval = 1.0)
t2 = tf.random.uniform(shape = (5,300), minval = 0, maxval = 1.0)

t2[:5]

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.12705207, 0.628549  , 0.06351662, ..., 0.04612827, 0.07539785,
        0.2848909 ],
       [0.49708343, 0.6589992 , 0.29942286, ..., 0.21471858, 0.61555433,
        0.11177218],
       [0.9940331 , 0.45074058, 0.20525706, ..., 0.60538447, 0.1356268 ,
        0.05405939],
       [0.8594179 , 0.9027289 , 0.9925448 , ..., 0.55624974, 0.30467582,
        0.74166095],
       [0.0413692 , 0.04575861, 0.72393215, ..., 0.02486563, 0.6420007 ,
        0.82562006]], dtype=float32)>

### 4. Multiply the two tensors created in 3 using matrix multiplication. ###

In [ ]:
t3 = tf.matmul(tf.transpose(t1), t2)
t3[:5]

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6345628 , 0.692763  , 0.75743955, ..., 0.39647788, 0.34211758,
        0.59875345],
       [0.74146676, 0.99100095, 0.88936967, ..., 0.45358962, 0.4229901 ,
        0.82182854],
       [2.0242581 , 1.988868  , 1.680872  , ..., 1.2125647 , 1.0192822 ,
        1.4496356 ],
       [1.0505229 , 1.1194472 , 0.95798194, ..., 0.59942156, 0.71998096,
        0.67525405],
       [1.6928017 , 1.659059  , 1.4039553 , ..., 0.97772264, 1.0467229 ,
        1.0153512 ]], dtype=float32)>

### 5. Multiply the two tensors created in 3 using dot product. ###

In [ ]:
t4 = tf.tensordot(tf.transpose(t1), t2, axes = 1)
t4[:5]

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6345628 , 0.692763  , 0.75743955, ..., 0.39647788, 0.34211758,
        0.59875345],
       [0.74146676, 0.99100095, 0.88936967, ..., 0.45358962, 0.4229901 ,
        0.82182854],
       [2.0242581 , 1.988868  , 1.680872  , ..., 1.2125647 , 1.0192822 ,
        1.4496356 ],
       [1.0505229 , 1.1194472 , 0.95798194, ..., 0.59942156, 0.71998096,
        0.67525405],
       [1.6928017 , 1.659059  , 1.4039553 , ..., 0.97772264, 1.0467229 ,
        1.0153512 ]], dtype=float32)>

### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]. ###

In [ ]:
t5 = tf.random.uniform(shape =  [224, 224, 3], minval = 0, maxval = 1)

### 7. Find the min and max values of the tensor in 6. ###

In [ ]:
print(f"Min value: {tf.math.reduce_min(t5)}")
print(f"Max value: {tf.math.reduce_max(t5)}")

Min value: 3.5762786865234375e-07
Max value: 0.9999961853027344


### 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]. ###

In [ ]:
t6 = tf.random.uniform(shape = [1, 224, 224, 3], minval = 0, maxval = 1)

t6 = tf.squeeze(t6)
print(t6.shape)

(224, 224, 3)


### 9. Create a tensor with shape [10], then find the index which has the maximum value. ###

In [ ]:
t7 = tf.range(0, 11)

print(tf.argmax(t7))

tf.Tensor(10, shape=(), dtype=int64)


### 10. One-hot encode the tensor created in 9. ###

In [ ]:
tf.one_hot(t7, depth = 10)

<tf.Tensor: shape=(11, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>